INFO:root:Program started
INFO:root:Robot set up!
INFO:root:Odometry was started, PID: 1916:
INFO:root:Initial location: 0.2, 1.8, -1.5707963267948966
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 54, in main
    oscar.navigateMap([0, 4], [4, 1])
  File "/home/pi/oscar/Robot.py", line 115, in navigateMap
    grid = self.remakeMap(size, map, goal, origin)
  File "/home/pi/oscar/Robot.py", line 123, in remakeMap
    pos = sage.pos2arr(size, map, [self.x.value, self.y.value])
AttributeError: module 'sage' has no attribute 'pos2arr'

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
