INFO:root:Program started
INFO:root:Robot set up!
INFO:root:Odometry was started, PID: 6184:
INFO:root:Initial location: 0.0, 0.0, 0.0
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 53, in main
    oscar.navigateMap([0, 0], [4, 1])
  File "/home/pi/oscar/Robot.py", line 113, in navigateMap
    arrived = gt.go_to(self, destination_coord)
  File "/home/pi/oscar/go_to4.py", line 18, in go_to
    while not sage.is_near(robor, pos):
NameError: name 'robor' is not defined

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
