INFO:root:Program started
INFO:root:Robot set up!
INFO:root:Odometry was started, PID: 2210:
INFO:root:Initial location: 0.0, 0.0, 0.0
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 53, in main
    oscar.navigateMap([0, 0], [4, 1])
  File "/home/pi/oscar/Robot.py", line 97, in navigateMap
    map_pos = sage.pos2map(size, map, origin, [self.x.value, self.y.value]) # calcula la pos que tiene en el mapa
  File "/home/pi/oscar/sage.py", line 209, in pos2map
    cell = pos / (2*size[2]) + origin
NameError: name 'size' is not defined

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
