INFO:root:Program started
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 24, in main
    oscar = Robot(init_position=[0.2, 1.8, math.pi])
  File "/home/pi/oscar/Robot.py", line 43, in __init__
    [self.map_size, self.map] = helpers.map.read_map(self.map)
AttributeError: 'Robot' object has no attribute 'map'

