INFO:root:Program started
INFO:root:Robot set up!
INFO:root:Odometry was started, PID: 19216:
INFO:root:Initial location: 0.2, 1.8, 3.141592653589793
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 57, in main
    actions.map.navigateMap(oscar, [0, 4], [4, 1])
  File "/home/pi/oscar/actions/map.py", line 48, in navigateMap
    arrived = go_to_cell(robot, map, relative_move, abs_destination, clockwise)   # recorremos el mapa hasta llegar a la siguiente celda
  File "/home/pi/oscar/actions/map.py", line 126, in go_to_cell
    actions.moves.arc(robot, goal)
  File "/home/pi/oscar/actions/moves.py", line 46, in arc
    robot.SetSpeed(0,0)
AttributeError: 'Robot' object has no attribute 'SetSpeed'

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
