INFO:root:Program started
INFO:root:Robot set up!
INFO:root:Odometry was started, PID: 6561:
INFO:root:Initial location: 0.2, 1.8, 3.141592653589793
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 57, in main
    actions.map.navigateMap(oscar, [0, 4], [4, 1])
  File "/home/pi/oscar/actions/map.py", line 44, in navigateMap
    helpers.map.draw_map(grid, offset_angle/2, arr_pos)
  File "/home/pi/oscar/helpers/map.py", line 14, in draw_map
    print(tabulate(ascii_grid, tablefmt='grid'))
TypeError: 'module' object is not callable

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
