INFO:root:MAIN: Program started
DEBUG:root:GENERATE_GRID: goal_k is: 0
 goals: [0, 0, 0]
INFO:root:ROBOT: Robot set up!
INFO:root:ROBOT: Odometry was started, PID: 4926:
INFO:root:MAIN: Initial location: 2.2, 2.6, -1.5707963267948966


INFO:root:ROBOT forceNewPosition: Updating position to [1.8, 1.4, -1.5707963267948966]
DEBUG:root:GENERATE_GRID: goal_k is: [7. 1.]
 goals: [array([7., 1.]), array([7., 7.])]
DEBUG:root:GENERATE_GRID: grid (Type <class 'numpy.ndarray'>) is:
[[-1.  7. -1. -1. -1. -1. -1. 13. -1. -1. -1. 21. -1. -1. -1.]
 [-1.  6.  7.  8.  9. 10. 11. 12. -1. 18. 19. 20. 21. 22. -1.]
 [-1.  5.  6.  7.  8.  9. 10. 11. -1. 17. 18. -1. 22. 21. -1.]
 [-1.  4.  5.  6.  7.  8.  9. 10. -1. 16. -1. -1. -1. 20. -1.]
 [-1.  3.  4.  5.  6.  7.  8.  9. -1. 15. 16. -1. 18. 19. -1.]
 [-1.  2.  3.  4.  5.  6.  7.  8. -1. 14. 15. 16. 17. 18. -1.]
 [-1.  1.  2.  3.  4.  5.  6.  7. -1. 13. 14. -1. 18. 17. -1.]
 [-1.  0.  1.  2.  3.  4.  5.  6. -1. 12. -1. -1. -1. 16. -1.]
 [-1.  1. -1. -1. -1. -1. -1.  7. -1. 11. 12. -1. 14. 15. -1.]
 [-1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. -1.]
 [-1.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. -1.]
 [-1.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. -1.]
 [-1.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. -1.]
 [-1.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/helpers/map.py", line 183, in generate_grid
    grids = np.append(grids, generate_single_grid(map, goal_k), axis = 0)
  File "<__array_function__ internals>", line 6, in append
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/lib/function_base.py", line 4693, in append
    return concatenate((arr, values), axis=axis)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 64, in main
    actions.map.navigate_map(oscar,oscar.objective)
  File "/home/pi/oscar/actions/map.py", line 88, in navigate_map
    robot.grid = helpers.map.generate_grid(map, goal)
  File "/home/pi/oscar/helpers/map.py", line 187, in generate_grid
    grid = generate_single_grid(map, goals)
  File "/home/pi/oscar/helpers/map.py", line 209, in generate_single_grid
    grid[int(goal[0]), int(goal[1])] = 0      # we set the goal to 0
TypeError: only size-1 arrays can be converted to Python scalars

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000.
DEBUG:matplotlib.axes._base:update_title_pos
DEBUG:matplotlib.axes._base:update_title_pos
DEBUG:matplotlib.axes._base:update_title_pos
