INFO:root:MAIN: Program started
DEBUG:root:GENERATE_GRID: no hay que mezclar
INFO:root:ROBOT: Robot set up!
INFO:root:ROBOT: Odometry was started, PID: 15935:
INFO:root:MAIN: Initial location: 2.2, 2.6, -1.5707963267948966
INFO:root:*---------------------------------------------------------------------------*
INFO:root:*---------------------------------------------------------------------------*
WARNING:root:Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1421, in capture
    if not encoder.wait(self.CAPTURE_TIMEOUT):
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 393, in wait
    result = self.event.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 297, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 72, in main
    found = helpers.vision.find_my_template(oscar)
  File "/home/pi/oscar/helpers/vision.py", line 97, in find_my_template
    frame = robot.takePic(PI=True)  # PI==True because its better for the template recognition
  File "/home/pi/oscar/Robot.py", line 232, in takePic
    self.cam.capture(rawCapture, format="bgr")
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1425, in capture
    encoder.close()
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 431, in close
    self.stop()
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 419, in stop
    self._close_output()
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 349, in _close_output
    mo.close_stream(output, opened)
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 371, in close_stream
    stream.flush()
  File "/usr/lib/python3/dist-packages/picamera/array.py", line 238, in flush
    self.array = bytes_to_rgb(self.getvalue(), self.size or self.camera.resolution)
  File "/usr/lib/python3/dist-packages/picamera/array.py", line 127, in bytes_to_rgb
    'Incorrect buffer length for resolution %dx%d' % (width, height))
picamera.exc.PiCameraValueError: Incorrect buffer length for resolution 640x480

WARNING:root:ABRUPT_STOP: abruptly stopped the robot!
DEBUG:matplotlib.axes._base:update_title_pos
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000.
DEBUG:matplotlib.axes._base:update_title_pos
