INFO:root:MAIN: Program started
INFO:root:ROBOT: Robot set up!
INFO:root:ROBOT: Odometry was started, PID: 14312:
INFO:root:MAIN: Initial location: 2.2, 2.6, -1.5707963267948966


WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 70, in main
    found = helpers.vision.find_my_template(oscar)
  File "/home/pi/oscar/helpers/vision.py", line 102, in find_my_template
    frame = robot.takePic(PI=True)
  File "/home/pi/oscar/Robot.py", line 220, in takePic
    cam = picamera.PiCamera()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 433, in __init__
    self._init_preview()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 513, in _init_preview
    self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
  File "/usr/lib/python3/dist-packages/picamera/renderers.py", line 558, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 2212, in enable
    prefix="Failed to enable connection")
  File "/usr/lib/python3/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000.
DEBUG:matplotlib.axes._base:update_title_pos
DEBUG:matplotlib.axes._base:update_title_pos
DEBUG:matplotlib.axes._base:update_title_pos
